name: Latest Release Version
description: Get latest (pre-)release's version of a repository, customized property name such as 'created_at' supported.
branding:
  icon: tag
  color: green
author: fangqiuming
inputs:
  repository:
    required: false
    description: Repository name with owner. For example, actions/runner
    default: ${{ github.repository }}
  token:
    required: false
    description: >
      Personal access token (PAT) used to read the repository.
      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.
      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}
  property:
    required: false
    description: Property name refers to version in [response object](https://docs.github.com/en/rest/reference/releases#get-the-latest-release)
    default: tag_name
  include_pre:
    required: false
    description: Include pre-release or not
    default: 'false'

outputs:
  tag_name:
    description: Tag name of the repository's latest release
    value: ${{ steps.main.outputs.tag_name }}
  version:
    description: Version value based on preferred property name
    value: ${{ steps.main.outputs.version }}
runs:
  using: composite
  steps:
    - run: |
        RESPONSE=$(curl -s --header 'authorization: Bearer ${{ inputs.token }}' https://api.github.com/repos/${{ inputs.repository }}/releases)
        if [[ $(jq -r '.[] | .created_at?' <<< $RESPONSE |  wc -l) -gt 0 ]]; then
          FILTER='.prerelease|not'
          if [[ include_pre == 'true' ]]; then FILTER='true'; fi
          TAG_NAME=$(jq -r "map(select($FILTER)) | first | .tag_name" <<< $RESPONSE)
          VERSION=$(jq -r "map(select($FILTER)) | first | .${{ inputs.property }}" <<< $RESPONSE)
        else
          TAG_NAME=v0.0.0
          VERSION=v0.0.0
        fi
        echo "TAG_NAME: $TAG_NAME"
        echo "VERSION: $VERSION"
        echo "::set-output name=tag_name::$(echo $TAG_NAME)"
        echo "::set-output name=version::$(echo $VERSION)"
      shell: bash
      id: main
